// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID        int64            `json:"id"`
	Content   string           `json:"content"`
	VideoID   int64            `json:"video_id"`
	UserID    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Like struct {
	ID        int64            `json:"id"`
	VideoID   pgtype.Int8      `json:"video_id"`
	UserID    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID          int64            `json:"id"`
	Auth0UserID string           `json:"auth0_user_id"`
	Username    string           `json:"username"`
	Email       string           `json:"email"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Video struct {
	ID           int64            `json:"id"`
	Title        string           `json:"title"`
	Description  string           `json:"description"`
	FileUrl      string           `json:"file_url"`
	ThumbnailUrl string           `json:"thumbnail_url"`
	UserID       string           `json:"user_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type VideoCategory struct {
	VideoID    int64 `json:"video_id"`
	CategoryID int64 `json:"category_id"`
}
