// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteUser(ctx context.Context, id int64) error
	DeleteVideo(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserVideoWithLikes(ctx context.Context, arg GetUserVideoWithLikesParams) ([]GetUserVideoWithLikesRow, error)
	GetVideo(ctx context.Context, id int64) (Video, error)
	GetVideoWithLikes(ctx context.Context, id int64) (GetVideoWithLikesRow, error)
	GetVideoWithLikesWithSearch(ctx context.Context, id int64) (GetVideoWithLikesWithSearchRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	ListVideosWithLikesAndSearch(ctx context.Context, arg ListVideosWithLikesAndSearchParams) ([]ListVideosWithLikesAndSearchRow, error)
}

var _ Querier = (*Queries)(nil)
